const fs = require('fs');
let c = fs.readFileSync('C:/Users/bekir demirel/Desktop/geobek/app.js', 'utf8');
c = c.replace(/Ã‡/g, 'Ç');
c = c.replace(/Ãœ/g, 'Ü');
c = c.replace(/Ä°/g, 'İ');
c = c.replace(/Åž/g, 'Ş');
c = c.replace(/Ã–/g, 'Ö');
c = c.replace(/ÄŸ/g, 'ğ');
c = c.replace(/Ã§/g, 'ç');
c = c.replace(/Ä±/g, 'ı');
c = c.replace(/Ã¼/g, 'ü');
c = c.replace(/Ã¶/g, 'ö');
c = c.replace(/ÅŸ/g, 'ş');
c = c.replace(/Ã„Â°/g, 'İ');
c = c.replace(/Ã„Å¸/g, 'ğ');
c = c.replace(/Ã„Â±/g, 'ı');
fs.writeFileSync('C:/Users/bekir demirel/Desktop/geobek/app.js', c, 'utf8');
